### ISSUE TITLE
Error in an example in docucmentation ?

### ISSUE THREAD

**Issue by meven** [auraphp/Aura.Marshal#1]
I read this in the example of the "Loading Data" section :

```
// add the authors for the posts.  first, we need to know
// the author_id values for all the posts so far ...
$author_ids = $manager->posts->getFieldValues('author_id');

// ... then we can query and load.
$result = $db->fetchAll(
    'SELECT * FROM authors WHERE id IN (?)',
    [$author_ids]
);
$manager->comments->load($result);
```

I think the last line should be '$manager->authors->load($result);' instead of '$manager->comments->load($result);'.
Am I right ?

**Comment by harikt** [comment]
Thank you @meven for reporting it . This fix will help https://github.com/auraphp/Aura.Marshal/pull/2

**Comment by pmjones** [comment]
Pulled and merged. Thanks, meven, for the report; thanks, harikt, for the fixes.

**Comment by harikt** [comment]
I have created a wiki page using PDO, the only trouble is the wiki is not rendering the mysql dump properly for it contains single quotes  https://github.com/auraphp/docs/wiki/Complete-Example-for-Aura.Marshal

**Comment by pmjones** [comment]
Fixed the dump; markdown requires 4-spaces for tabs to recognize it as a code block. Looks nice harikt, thanks!

**Comment by harikt** [comment]
@pmjones  Thanks and cool .. But I wonder why it didn't worked for me . I created the 4 spaces :-( . But I am Happy that its resolved :) .

**Comment by harikt** [comment]
Aaah understood , it only moved 2 spaces :P . Crap :D .

**Comment by harikt** [comment]
I feel its a good idea to link to the wiki page from the README,  for it works with PDO . Thoughts ?
