### ISSUE TITLE
Add some kind of a "clear" functionality.

### ISSUE THREAD

**Issue by immutef** [auraphp/Aura.Marshal#11]
In longer running processes or entity-heavy processes it may occur that you reach the memory_limit of PHP. Increasing it may not be an option, but I'd like to see some kind of clearance for the loaded entities to free some space (e.g., after a round of batch processing several thousand entities, remove everything that was loaded so far). As far as I could guess I think Marshal works similar to the Doctrine2 UnitOfWork, keeping references to generated object instances and reusing them. Doctrine2 has the same problem if you don't clear the UnitOfWork on a regular basis.

See the Doctrine2 UnitOfWork to get some sort of an idea:
- https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/UnitOfWork.php#L1455
- https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/UnitOfWork.php#L2342

I think this feature should be proposed for the 2.0 version of Marshal?

**Comment by pmjones** [comment]
If I understand what you're asking for, that could totally go into v1 without any BC breaks.
1. Add a "clear()" or equivalent method on all Type objects, to release the Entity objects from memory. (This does not imply deleting them or anything, it just unsets the references.)
2. Add a "clear()" or equivalent method on the Manager, to loop through the Type objects and call "clear()" on each of them.

Does that sound about right?

**Comment by immutef** [comment]
Yes, both sounds right. Haven't had the time yet to check where the references are stored but I think that would solve the problem.

Von meinem iPad gesendet
