### ISSUE TITLE
Problem with GenericLazy when using my own entity

### ISSUE THREAD

**Issue by shina** [auraphp/Aura.Marshal#12]
I experienced some trouble when implementing my own entity because of the GenericLazy. 

I figured out that \Aura\Marshal\Entity\MagicArrayAccessTrait make the "transformation" of the GenericLazy to the real class. But MagicArrayAccessTrait only works with an implementation of \ArrayAccess, that is made with \Aura\Marshal\Data.

So, I had to extends \Aura\Marshal\Data and use \Aura\Marshal\Entity\MagicArrayAccessTrait to make my entity works properly.

Should be good if MagicArrayAccessTrait makes the whole thing alone.
And it documented on README.md

**Comment by pmjones** [comment]
If you could show examples of what you had to do to make it work for you, that would help.

**Comment by shina** [comment]
This is an example of the entity
https://gist.github.com/shina/9c130e3b0bfc728819b6

MagicArrayAccessTrait uses the following code to convert the GenericLazy to the real class
if ($value instanceof LazyInterface) {
      // replace the Lazy placeholder with the real object
      $value = $value->get($this);
      $this->offsetSet($field, $value);
}

But the class need to implement the \ArrayAccess interface, and \Aura\Marshal\Data implement it. But it's not good extend a foreign class.

Hope you understand

**Comment by pmjones** [comment]
At least in theory, you should not have to extend Aura\Marshal\Data at all for your own entities. The MagicArrayAccessTrait only looks to see if a value is a LazyInterface, and that doesn't make any calls to the Data class. The entity class _does_ have to implement ArrayAccess, and that's something you should do yourself with your entity class (or base entity class) like so:

https://gist.github.com/pmjones/8061259

Alternatively, your entity classes can declare protected properties, and you can use MagicPropertyTrait instead, like so:

https://gist.github.com/pmjones/8061289

What am I missing here?

**Comment by shina** [comment]
The problem is the mandatory implementation of ArrayAccess. Ok, implement ArrayAccess is not a big deal, but I think it could be better.

IMHO
At least is to explain people about the GenericLazy and how to use it with MagicArrayAccessTrait.

Another solution, but now I'm not so certain about it, is to create 1 Trait that handles everything about the GenericLazy.

**Comment by harikt** [comment]
I think this issue can be closed. I came to the exact same issue and fixed with a getter which removed the offsetGet 

``` php
<?php
namespace AuraBook\Blog\Entity;

use Aura\Marshal\Lazy\LazyInterface;

class Post
{
    protected $id;

    protected $title;

    protected $description;

    protected $tags;

    protected $author;

    public function __construct($title = '', $description = '', $tags = '', $author = '', $id = '')
    {
        $this->title = $title;
        $this->description = $description;
        $this->tags = $tags;
        $this->author = $author;
        $this->id = $id;
    }

    public function __get($field)
    {
        // get the field value
        $value = $this->$field;

        // is it a Lazy placeholder?
        if ($value instanceof LazyInterface) {
            // replace the Lazy placeholder with the real object
            $value = $value->get($this);
            $this->$field = $value;
        }

        // done!
        return $value;
    }

    public function __set($field, $value)
    {
        $this->$field = $value;
    }

    public function __isset($field)
    {
        return isset($this->$field) ? true : false;
    }

    public function __unset($field)
    {
        unset($this->$field);
    }
}
```

**Comment by harikt** [comment]
aah, this could have been simpler as

``` php
<?php
namespace AuraBook\Blog\Entity;

use Aura\Marshal\Lazy\LazyInterface;
use Aura\Marshal\Entity\MagicPropertyTrait;

class Post
{
    use MagicPropertyTrait;

    protected $id;

    protected $title;

    protected $description;

    protected $tags;

    protected $author;

    public function __construct($title = '', $description = '', $tags = '', $author = '', $id = '')
    {
        $this->title = $title;
        $this->description = $description;
        $this->tags = $tags;
        $this->author = $author;
        $this->id = $id;
    }
}
```

My bad :) .

**Comment by pmjones** [comment]
Closing per @harikt .
