### ISSUE TITLE
DataIterator should depend on ArrayAccess, not Data

### ISSUE THREAD

**Issue by djmattyg007** [auraphp/Aura.Marshal#16]
The Aura\Marshal\DataIterator constructor expects an instance of Aura\Marshal\Data, but the only method it calls on the Data object is offsetGet(), which is part of the ArrayAccess interface. Is there any reason why the DataIterator constructor can't be modified to expect ArrayIterator rather than Data?

**Comment by harikt** [comment]
@djmattyg007 I am not good in this to comment. 

Please wait for Paul to respond. He is working on other packages.
