### ISSUE TITLE
'WiringAssertionsTrait' not found when running (php)unit tests

### ISSUE THREAD

**Issue by sobstel** [auraphp/Aura.Marshal#21]
```
Aura.Marshal git:develop ❯ phpunit tests
```

``` php
PHP Fatal error:  Trait 'Aura\Framework\Test\WiringAssertionsTrait' not found in /Users/sobstel/Projects/Aura.Marshal/tests/WiringTest.php on line 8

Fatal error: Trait 'Aura\Framework\Test\WiringAssertionsTrait' not found in /Users/sobstel/Projects/Aura.Marshal/tests/WiringTest.php on line 8
```

**Comment by harikt** [comment]
So you ran the tests from the root folder.

See travis how the tests runs https://github.com/auraphp/Aura.Marshal/blob/develop/.travis.yml#L6 .

``` php
cd tests
phpunit
```

**Comment by harikt** [comment]
Aah you don't need to run the wiringAssertionTest . It is there for the framework to tests. So you need to skip the https://github.com/auraphp/Aura.Marshal/blob/develop/tests/WiringTest.php
