### ISSUE TITLE
Allow protected/private properties without magic method

### ISSUE THREAD

**Issue by marcj** [auraphp/Aura.Marshal#25]
Currently https://github.com/auraphp/Aura.Marshal/blob/1.x/src/Aura/Marshal/Entity/Builder.php#L49 forces you to have public properties or using one of the provided traits which define `__set` magic method.

To allow having entities without this magic, I'd recommend to improve the Entity\Builder a bit to write into private/protected properties directly using a class bound setter function.

So instead of doing

``` php
foreach ($data as $field => $value) {
     $entity->$field = $value;
}
```

we could do

``` php
$writer = \Closure::bind(
    function ($object, $prop, $value) {
        $object->$prop = $value;
    },
    null,
    get_class($entity)
);

foreach ($data as $field => $value) {
     $writer($entity, $field, $value);
}
```

@pminnieur

**Comment by pmjones** [comment]
Nifty! If you want to send a PR for that I'll review it; that way you get automatic credit for it on the contributors list.
