### ISSUE TITLE
Entity to array?

### ISSUE THREAD

**Issue by retardedHacker** [auraphp/Aura.Marshal#27]
Lets say you have loaded data with relations and now wants to serialize / json your data

```
// get a collection of the post IDs we just loaded
$posts = $manager->posts->getCollection($post_ids);

print_r($posts[0]); //will throw me huge pile of code that kills my browser. 
```

Sure I could build an array by accessing individual properties like $posts[0]->name... And so on,but that's not convenient.

**Comment by harikt** [comment]
I think you could use http://php.net/iterator_to_array to get the array values. 

Does that help you ?

**Comment by retardedHacker** [comment]
I'm afraid not, because it's doesn't remove all the clutter..

**Comment by pmjones** [comment]
I hate saying it, but feature additions on this package in its 1.x state are effectively at an end.

You should be able to create your own Entity and Collection objects with that functionality, though. Cf. <https://github.com/auraphp/Aura.Marshal#entity-and-collection-builders> for how to incorporate builders, which can then instantiate your own objects.

**Comment by flip111** [comment]
> I hate saying it, but feature additions on this package in its 1.x state are effectively at an end.

Is there a successor of this package somewhere? Or perhaps someone knows alternative packages? I'm not sure if i should still be using this in a new project or not.

**Comment by harikt** [comment]
@flip111 I am not aware of an alternative package. From the 3.x plans http://auraphp.com/blog/2015/03/27/aura-3-plans/

> Aura 1.x framework packages will see no new releases, and may be archived.
> Aura 1.x library packages are near the end of active development; to prevent orphaning and end-of-life, ownership and authority over them they may be transferred to interested parties.

You can read a more detailed explanation there.
