### ISSUE TITLE
Document new use case: marshaling data from API sources

### ISSUE THREAD

**Issue by compwright** [auraphp/Aura.Marshal#28]
The examples are database-centric, it would be nice to have an example or documentation related to using this in an API context.

This does appear to be a use case that exists. Searching [Packagist](https://packagist.org) for terms such as `api relationship` or `data relationship` returns a small handful of libraries.

Most of these are unsuitable for some reason, such as lack of maintenance, poor documentation, or tight binding to a particular ORM (such as Doctrine) or framework (such as Laravel). However these two stand out as possibilities:

* https://github.com/MartialGeek/relationships-data-transformer
* https://github.com/aaronbullard/dogpile

Neither of these are as elegant or well documented as Aura.Marshal.

As an aside, Aura.Marshal is the top hit for the search term `data relationship`. It would be nice for this to show up in the `api relationship` search results as well.

**Comment by harikt** [comment]
Send a PR with your suggestions. I will consider merging it.

**Comment by harikt** [comment]
Is there any other issues other than this you noticed ? If not we can do a beta release of 4.x .

UPDATE : I have released 4.0.0-beta.1 .

**Comment by compwright** [comment]
@harikt not to my knowledge. The documentation could stand to be expanded but that doesn't need to block release.

**Comment by harikt** [comment]
cool.
