### ISSUE TITLE
Officially support PHP 7-8

### ISSUE THREAD

**Issue by compwright** [auraphp/Aura.Marshal#29]
This probably works fine in later versions of PHP, but it would be helpful if this were proven and noted.

**Comment by harikt** [comment]
4.x branch created. CI updated . It may take some time to get a 4.x release. But I hope we can do with the next 2 week if there is no major changes required.

**Comment by harikt** [comment]
I am closing this issue for now. In case I didn't make a release just ping me.

Thank you.
