### ISSUE TITLE
Convert to array

### ISSUE THREAD

**Issue by compwright** [auraphp/Aura.Marshal#32]
Some use cases require using plain PHP arrays, but getCollection() returns an object.

A naive conversion fails:

```php
$array = iterator_to_array(
    $manager->getCollection(...)->getIterator()
);
```

This fails because although $array is an array, its elements are objects of class `Aura\Marshal\Entity\GenericEntity`.

If this can be done with a custom builder, then a documentation example for that should be added.

**Comment by harikt** [comment]
I know you would have came across this https://github.com/auraphp/Aura.Marshal#entity-and-collection-builders . But I have not tested adding a JsonSerialize or toArray inside the [GenericEntity](https://github.com/auraphp/Aura.Marshal/blob/0c75afae8558b5e02b29f69a23bb5eb33b9a95b8/src/Entity/Builder.php#L31) to check whether it will convert to array when you do iterator_to_array .

**Comment by compwright** [comment]
It will not. I had to implement a custom CollectionBuilder and EntityBuilder. See my implementation here: https://gist.github.com/compwright/39854ef748ae75da701fbf2036bcf60d

I believe this is a significant feature gap in a library that expects data to be provided in array form. You should be able to get the data out in array form as well.

**Comment by harikt** [comment]
@compwright yes, I was referring to creating custom builder. I am not sure if I can find some time to look into this.

We can probably implement the JsonSerializable interface which can return array.

**Comment by harikt** [comment]
@compwright are you in a position to send a pull request with those changes as you mentioned in gist to 4.x ?

I will be happy to merge.

**Comment by compwright** [comment]
@harikt done, https://github.com/auraphp/Aura.Marshal/pull/38
