### ISSUE TITLE
Exception should not be raised

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Marshal#6]
I have 3 posts , with ids 1, 2, 3 . If there is no summary for 3rd post 

```
 post_id      read_sum
 1              4
 2                 2
```

trying to get `$post->summary->read_sum` will throw exception. I feel it should not throw the exception. Playing on develop branch with the same example in README.md .

**Comment by pmjones** [comment]
If there's no summary, there probably ought to be a warning of _some_ sort that the data is not loaded. If not an exception, what do we think should happen instead?

**Comment by harikt** [comment]
I am not sure, but probably suppress the error ?

**Comment by texdc** [comment]
If there is no matching record, the relation should be null.  Therefore, attempting to access a property of null would trigger a fatal error revealing an implementation flaw.

**Comment by harikt** [comment]
@texdc so, do you think that we can do anything here ?

**Comment by gpapadopg** [comment]
A better way is to assign a ZERO value/NULL Object/NULL Collection (take a look for example [here](http://phpmaster.com/the-null-object-pattern-polymorphism-in-domain-models/)). But this kind of logic belongs into the domain model **and not** into the marshal package. The null object may instantiated via a builder/factory (as marshal [does](https://github.com/auraphp/Aura.Marshal#entity-and-collection-builders)).

eg, for this case (posts and summaries), the model object should initialized with a summaries count of zero, or a better alternative, with a SummariesCollection object, having (the collection) zero elements. Then, the marshal is responsible to populate the summaries count/collection.

My suggestion: For the specific examples the generic builder must take into account the relations to build the children objects - but i don't know if this violates some OOP principles (is it proper for the generic builder to know the relationship between the objects?)

Another alternative would be to update the examples with full defined domain objects only :-)

**Comment by harikt** [comment]
Interesting and Thanks guys!

**Comment by pmjones** [comment]
I'm still OK with the exception; if we feel the examples should be changed, I can review a PR over the next few days.
